# coding: utf-8

# flake8: noqa

"""
    Demo Client for Passmeister Apple Wallet and Google Wallet API

    [www.passmeister.com](https://www.passmeister.com).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.pass_api import PassApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
