# coding: utf-8

# flake8: noqa
"""
    Demo Client for Passmeister Apple Wallet and Google Wallet API

    [www.passmeister.com](https://www.passmeister.com).  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
